[package]
name = "cmvm"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { features = ["derive"] }
dirs = "4.0.0"
parse_link_header = "0.3"
reqwest = { version = "0.11.9", features = ["blocking", "json"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
flate2 = "1.0.22"
tar = "0.4.38"
fs_extra = "1.2.0"
lazy_static = "1.4.0"